https://github.com/noehurtado/diabetes/blob/64eabc8a16056885663521b215c2712cb310174c/src/explore.ipynb

# **0. CONTEXTO**

Fuente: https://github.com/4GeeksAcademy/logistic-regression-project-tutorial/blob/main/README.es.md

Descripción de variables:

- age. Edad del cliente (numérico)

- job. Tipo de trabajo (categórico)

- marital. Estado civil (categórico)

- education. Nivel de educación (categórico)

- default. ¿Tiene crédito actualmente? (categórico)

- housing. ¿Tiene un préstamo de vivienda? (categórico)

- loan. ¿Tiene un préstamo personal? (categórico)

- contact. Tipo de comunicación de contacto (categórico)

- month. Último mes en el que se le ha contactado (categórico)

- day_of_week. Último día en el que se le ha contactado (categórico)

- duration. Duración del contacto previo en segundos (numérico)

- campaign. Número de contactos realizados durante esta campaña al cliente (numérico)

- pdays. Número de días que transcurrieron desde la última campaña hasta que fue contactado (numérico)

- previous. Número de contactos realizados durante la campaña anterior al cliente (numérico)

- poutcome. Resultado de la campaña de marketing anterior (categórico)

- emp.var.rate. Tasa de variación del empleo. Indicador trimestral (numérico)

- cons.price.idx. Índice de precios al consumidor. Indicador mensual (numérico)

- cons.conf.idx. Índice de confianza del consumidor. Indicador mensual (numérico)

- euribor3m. Tasa EURIBOR 3 meses. Indicador diario (numérico)

- nr.employed. Número de empleados. Indicador trimestral (numérico)

- y. TARGET. El cliente contrata un depósito a largo plazo o no (categórico)

In [1]:
import numpy as np
import pandas as pd
import missingno as msno

In [2]:
#Cargamos la base de datos en crudo
df_raw=pd.read_csv("https://storage.googleapis.com/breathecode/project-files/bank-marketing-campaign-data.csv", sep=";")
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [3]:
df_raw.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

# **1. CRIBADO MANUAL**

In [1]:
#No hay variables redundantes

## 1.2. Limpieza de datos y estudio de missing values

#### A.2) Categorización

**TEORÍA**

- map Género, 1,2,3

- target encoding

- frecuency encoding

- one-hot encoding


Opciones para categorizar una variable: https://datos.ninja/tutorial/como-codificar-variables-categoricas/

- One hot encoding: dummy por categoria &rarr; se produce cuando no hay diferencias significativas en medias

- Target encoding: toma como categoria la media de y por cada valor de la categorica (https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.TargetEncoder.html)

- Ordinal encoding: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html

In [106]:
df_raw["job"].value_counts().sort_index()

job
admin.           10419
blue-collar       9253
entrepreneur      1456
housemaid         1060
management        2924
retired           1718
self-employed     1421
services          3967
student            875
technician        6739
unemployed        1014
Name: count, dtype: int64

In [107]:
df_raw["job"].astype("category").cat.codes.value_counts()

 0     10419
 1      9253
 9      6739
 7      3967
 4      2924
 5      1718
 2      1456
 6      1421
 3      1060
 10     1014
 8       875
-1       330
Name: count, dtype: int64

In [73]:
df["job"]=df_raw["job"].value_counts().astype("category").cat.codes

NameError: name 'df' is not defined

In [23]:
df_raw["job"].astype("category").cat.codes.value_counts().sort_index()

0     10419
1      9253
2      1456
3      1060
4      2924
5      1718
6      1421
7      3967
8       875
9      6739
10     1014
11      330
Name: count, dtype: int64

In [ ]:
df_raw.groupby("job")[""]

### B) Númericas (float)

In [32]:
df_raw.select_dtypes(include='float64')

       emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed
0               1.1          93.994          -36.4      4.857       5191.0
1               1.1          93.994          -36.4      4.857       5191.0
2               1.1          93.994          -36.4      4.857       5191.0
3               1.1          93.994          -36.4      4.857       5191.0
4               1.1          93.994          -36.4      4.857       5191.0
...             ...             ...            ...        ...          ...
41183          -1.1          94.767          -50.8      1.028       4963.6
41184          -1.1          94.767          -50.8      1.028       4963.6
41185          -1.1          94.767          -50.8      1.028       4963.6
41186          -1.1          94.767          -50.8      1.028       4963.6
41187          -1.1          94.767          -50.8      1.028       4963.6

[41188 rows x 5 columns]

### B) Númericas (int)

In [37]:
df_raw.select_dtypes(include='int64')

       age  duration  campaign  pdays  previous
0       56       261         1    999         0
1       57       149         1    999         0
2       37       226         1    999         0
3       40       151         1    999         0
4       56       307         1    999         0
...    ...       ...       ...    ...       ...
41183   73       334         1    999         0
41184   46       383         1    999         0
41185   56       189         2    999         0
41186   44       442         1    999         0
41187   74       239         3    999         1

[41188 rows x 5 columns]

In [40]:
df_raw["job"].value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [41]:
df_raw["job"].isna()

0        False
1        False
2        False
3        False
4        False
         ...
41183    False
41184    False
41185    False
41186    False
41187    False
Name: job, Length: 41188, dtype: bool